config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers=> { registrations: "users/registrations", confirmations: "users/confirmations", sessions: "users/sessions", passwords: "users/passwords"}
  resources :messages
  resources :rooms

  post 'go_live' => 'messages#go_live'
  root 'rooms#index'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  # before_action :set_room, only: %i[ create ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    # respond_to do |format|
      # if @message.save
        @message.save
        # redirect_to request.referrer
        # format.html { redirect_to @message, notice: "Message was successfully created." }
        # format.json { render :show, status: :created, location: @message }
        # format.js {render 'show'}
      # else
      #   format.html { render :new, status: :unprocessable_entity }
      #   format.json { render json: @message.errors, status: :unprocessable_entity }
      # end
    # end

    # html = render(partial: 'messages/message', locals: { message: @message })
    # ActionCable.server.broadcast "room_channel_#{@message.room_id}", {message: html}
    SendMessageJob.perform_later(@message)
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def go_live 
    r= rand(1..1000)
    directory_name = "#{Rails.root}/public/cam/"
    Dir.mkdir(directory_name) unless File.exists?(directory_name)
    DeleteImageJob.set(wait: 2.minutes).perform_later(r)
    # FileUtils.rm_rf(Dir.glob("#{directory_name}*"))
    File.open("#{directory_name}#{r}.png", 'wb') do |f|
      f.write(params[:image].read)
    end
    CameraJob.perform_later(r, params[:channel], current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id, :room_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true, class: 'form-inline') do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <%= form.hidden_field :room_id, value: room.id %>
  <div class="input-group w-100">
    <%= form.text_field :content, placeholder: 'Type your message here...', class: 'form-control mr-2' %>
    <div class="input-group-append">
      <%= form.submit "Add Message", class: 'btn btn-primary send_message_btn' %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="message mb-2 <%= 'me' if message.user == current_user %>">
    <div class="content-container">
      	<div class="content">
        	<%= message.content %>
      	</div>
      	<div class="author">
        	<%= message.user.username %>
      	</div>
    </div>
</div>

app/views/messages/_receiver.html.erb
<div class="message mb-2">
    <div class="content-container">
      	<div class="content">
        	<%= message.content %>
      	</div>
      	<div class="author">
        	<%= message.user.username %>
      	</div>
    </div>
</div>

app/views/messages/_sender.html.erb
<div class="message mb-2 me">
    <div class="content-container">
      	<div class="content">
        	<%= message.content %>
      	</div>
      	<div class="author">
        	<%= message.user.username %>
      	</div>
    </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.user_id %></td>
        <td><%= message.room_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @message.room_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>