config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers=> { registrations: "users/registrations", confirmations: "users/confirmations", sessions: "users/sessions", passwords: "users/passwords"}
  resources :messages
  resources :rooms

  post 'go_live' => 'messages#go_live'
  root 'rooms#index'
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :messages
	has_many :users, through: :messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @rooms = Room.all
    render 'index'
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_room
    #   @room = Room.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p><b>Create a new room</b></p>

  <div class="form-group mb-3">
    <%= form.label "Create a new room" %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Room name' %>
  </div>

  <div class="actions">
    <%= form.submit "Add Room", class: 'btn btn-outline-primary btn-block' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div id="user-id" data-user-id="<%= current_user.id if user_signed_in? %>"></div>
<div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3 col-xl-3 col-md-3 col-sm-12 col-xs-12">
      <div class="card no-outline">
<!--         <div class="card-body">
          <small>
            Logged in as
          </small></br>
          <b>
            <%#= current_user.username%>
          </b>          
        </div> -->
      </div>
      <hr>
      <%= render 'form', room: Room.new %>
      <hr>
      <% @rooms.each do |room| %>
        <%= link_to room, class: 'room-link' do %>
        <% active_class = (@room == room) ? 'active' : '' %>
        <div class="card no-outline mb-2 room-card <%= active_class %>">
          <div class="card-body">
            <b><%= room.name %></b></br>
            <span class="member-count">
              <small><%= room.users.uniq.count %> Members</small>
            </span>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-lg-9 col-xl-9 col-md-9 col-sm-12 col-xs-12">
      <% if @room.present? %>
        <div class="chat-room pt-5">
          <nav class="navbar navbar-light bg-light mb-4">
            <span class="navbar-brand"><%= @room.name  %></span>
            <div class="pull-right">
              <button class="btn btn-primary" id="go_live">
                Go Live
              </button>
            </div>
          </nav>
          <div id="video_container" class="video_container p-4 mb-5">
            <video id="video" width="640" height="480" controls style="width: 0"></video>
            <canvas id="canvas" width="640" height="480" style="width: 0px;"></canvas>
            <img id='ima' style="width: 100%;">
          </div>
          <div id="message" style="margin-bottom: 100px;">
            <% @room.messages.each do |message| %>
              <%= render 'messages/message', message: message %>
            <% end %>
          </div>
          <div class="chat-box">
            <%= render 'messages/form', message: Message.new, room: @room %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function dataURLtoBlob(dataURL){
    binary = atob(dataURL.split(',')[1])
    array = []
    i = 0
    while(i < binary.length) {
      array.push(binary.charCodeAt(i))
      i++
    }
    return new Blob([ new Uint8Array(array) ], {type: 'image/png'})
  }

  document.getElementById("go_live").addEventListener("click", function() {
    const room_element = document.getElementById('room-id')
    canvas = document.getElementById('canvas')
    navigator.mediaDevices.getUserMedia({video: true})
    .then(function(stream) {
      console.log(stream)

      document.getElementById('video_container').style.display = 'block'
      document.getElementById('video').style.width = '100%'
      document.getElementById('ima').style.width = '100%'
      video = document.querySelector('video')
      
      // if ('srcObject' of video){
        video.srcObject = stream
      // }
      // else{
        // video.src = window.URL.createObjectURL(stream)
      // }
      let i;

      video.play()
      video.onplay = (() => {
        if (canvas) {
          context = canvas.getContext('2d')
          i = window.setInterval(() => {
            context.drawImage(video, 0, 0, 640, 480)
            file = dataURLtoBlob(canvas.toDataURL())
            fd = new FormData
            fd.append('image', file)
            fd.append('channel', Number(room_element.getAttribute('data-room-id')))
            $.ajax({
              type: 'POST',
              url: '/go_live',
              data: fd,
              processData: false,
              contentType: false
            })
          },250)
        }
      })

      video.onpause = (() => {
        window.clearInterval(i)
      })
      // video.onended = ->
      //   window.clearInterval i
    })
    .catch(function(err) {
      console.log(err)
    });
  });
</script>


<!-- <h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @rooms.each do |room| %>
      <tr>
        <td><%#= room.name %></td>
        <td><%#= link_to 'Show', room %></td>
        <td><%#= link_to 'Edit', edit_room_path(room) %></td>
        <td><%#= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Room', new_room_path %> -->

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>